# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='namd',
            new_name='name',
        ),
    ]
